name: todo_online
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-348.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  loading_overlay: ^0.3.0
  flutter_keyboard_visibility: ^5.4.1
  cached_network_image: ^3.2.3
  firebase_core: ^2.14.0
  # cloud_firestore: ^4.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  package_rename: ^1.3.3
  build_runner: ^2.4.3
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  very_good_analysis: ^4.0.0+1
  hive_generator: ^2.0.0
flutter:
  uses-material-design: true

package_rename_config:
  android:
    app_name: Task Master 
    package_name: com.task.master

  ios:
    app_name: Task Master 
    bundle_name: taskMaster
    package_name: com.task.master
  web:
    app_name: Task Master Web
    description: A mobile application that turns your to-do list into a competition. You complete your tasks while competing with your friends.
